# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:98gK0KqyQs0Q5upjrJID4+HSgNV04o8fKa3ASxg+ROm7Czqawg==,iv:Jl1o1tr6p525KQ9JXi0cqQFTSHPYsuFAXaIkFMNTdA4=,tag:oUrysntkyCuhZbmEjZGXMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCckxhV3NqaTdweXRFYW01
            a2R3SldvbVVVY0syVXp1Qk11U3hWNjFXRFNFCnhZOEJycURpbW5YQlJpR1pOb1Jl
            WWtoL3hINm9OYjFlVHdtRU00QVI4WU0KLS0tIC9lU0txb3AxQmQ5U1A3SDgyVXZh
            Zy92c0xxRXFna2lqRU9LaFV5OVJDWU0KqShd/mTxbRX1hVS+FiEFU76pI5+0KEyf
            iWpgEIvGr52J1CSTPvODnUjDuhCV3PTrT5GChjfdp6ecvk40EfZSJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-24T09:42:12Z"
    mac: ENC[AES256_GCM,data:rMxpVXZWFEBd7KWYSya9jJYVUkjodQn/oMEKWBolOmwjY7prfTvQ8bVDuMoQc9xfWQJIm5IXaFL/nuMx6jwPK0+WaVDAuKvFBqh309zTkX8VkQoK160NAphw8+AjC4NqQjjtIhodxSiobsTGGSlJWhZahtM9RdvwwngkwmNURI0=,iv:fzfoC3qwt6Pk7buBLJyoX0SOOo4iAkOU/yf1ERWNsJU=,tag:BlgxX9pz5f2es3fljWmKGQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
